services:
  - type: web
    name: sp-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        generateValue: true
      - key: CLIENT_ID
        scope: runtime
      - key: CLIENT_SECRET
        scope: runtime
      - key: REFRESH_TOKEN
        scope: runtime
      - key: AWS_ACCESS_KEY
        scope: runtime
      - key: AWS_SECRET_KEY
        scope: runtime
